version: '3'

services:
  redis:
    image: redis:latest
    container_name: assign-redis
    ports:
      - "16379:6379"
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf

volumes:
  redis-data:
    driver: local
