@server=http://localhost:8080
@token=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJyeWVvbkB0ZXN0LmNvbSIsImlzcyI6InJzdXBwb3J0LWFzc2lnbi1ub3RpLXNlcnZlciIsImlhdCI6MTcxMDY0MDg0MSwiZXhwIjoxNzEwNzI3MjQxLCJlbWFpbCI6InJ5ZW9uQHRlc3QuY29tIiwiYWRtaW4iOiJhZG1pbiJ9.ZLA9ql2K20IMeks-IwJ4EUo1hBZYopCH1in9w2-dMTE

### token 발행 
GET {{server}}/api/token?email=ryeon@test.com

### 첨부파일 조회
GET {{server}}/file/download/76955aa9-45e0-46db-bcb9-7dbde15e231d

### 첨부파일 업로드
POST {{server}}/file/upload
Authorization: Bearer {{token}}
Content-Type: multipart/form-data; boundary=BOUNDARY

--BOUNDARY
Content-Disposition: form-data; name="files"; filename="uploadSample.txt"
Content-Type: text/plain

{ "name": "jane" }

--BOUNDARY
Content-Disposition: form-data; name="files"; filename="uploadSample2.txt"
Content-Type: text/plain

{ "name": "jane doe" }

--BOUNDARY--





















### test
GET {{server}}/noti/test
Authorization: Bearer {{token}}

### 목록 조회 
GET {{server}}/noti/list

### 등록
POST {{server}}/noti/create
Authorization: Bearer {{token}}
Content-Type: multipart/form-data; boundary=BOUNDARY

--BOUNDARY
Content-Disposition: form-data; name="title"

input test
--BOUNDARY
Content-Disposition: form-data; name="content"

description test
--BOUNDARY
Content-Disposition: form-data; name="file"; filename="uploadSample2.txt"

{ "name": "jane doe" }
--BOUNDARY--




 
### 단건 조회
GET {{server}}/noti/detail/1

### 수정
PUT {{server}}/noti/7
Authorization: Bearer {{token}}
Content-Type: multipart/form-data; boundary=BOUNDARY

--BOUNDARY
Content-Disposition: form-data; name="title"

input test updated
--BOUNDARY
Content-Disposition: form-data; name="content"

description test updated
--BOUNDARY
Content-Disposition: form-data; name="openDateTime"

2023-01-01T00:10:00
--BOUNDARY
Content-Disposition: form-data; name="file"; filename="uploadSample2.txt"

{ "name": "jane doe" }
--BOUNDARY--









PUT {{server}}/noti/1
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "title": "input test updated",
  "description": "input test content",
  "openDateTime": "",
  "fileUrlList": ["url1", "url2"]
}

### 삭제
DELETE {{server}}/noti/1
Authorization: Bearer {{token}}