@server=http://localhost:8080
@token=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJyeWVvbkB0ZXN0LmNvbSIsImlzcyI6InJzdXBwb3J0LWFzc2lnbi1ub3RpLXNlcnZlciIsImlhdCI6MTcxMDcyNzU1MywiZXhwIjoxNzEwODEzOTUzLCJlbWFpbCI6InJ5ZW9uQHRlc3QuY29tIiwiYWRtaW4iOiJhZG1pbiJ9.mPbtStEnf9xpFeQOgNoBIGXyAXyAjZ7WFGJoWYvnpvE

### token 발행 
GET {{server}}/api/token?email=ryeon@test.com

### 첨부파일 조회
GET {{server}}/file/download/76955aa9-45e0-46db-bcb9-7dbde15e231d

### 단일 첨부파일 업로드
POST {{server}}/file/upload/single
Authorization: Bearer {{token}}
Content-Type: multipart/form-data; boundary=BOUNDARY

--BOUNDARY
Content-Disposition: form-data; name="file"; filename="uploadSample.txt"
Content-Type: text/plain

{ "name": "jane" }
--BOUNDARY--



### 다중 첨부파일 업로드
POST {{server}}/file/upload/multiple2
Authorization: Bearer {{token}}
Content-Type: multipart/form-data; boundary=BOUNDARY

--BOUNDARY
Content-Disposition: form-data; name="files"; filename="uploadSample.txt"
Content-Type: text/plain

{ "name": "jane" }

--BOUNDARY
Content-Disposition: form-data; name="files"; filename="uploadSample2.txt"
Content-Type: text/plain

{ "name": "jane doe" }

--BOUNDARY--





















### test
GET {{server}}/noti/test
Authorization: Bearer {{token}}

### paging list
GET {{server}}/noti/list?page=1&size=1

### 등록
POST {{server}}/noti/create
Authorization: Bearer {{token}}
Content-Type: multipart/form-data; boundary=BOUNDARY

--BOUNDARY
Content-Disposition: form-data; name="title"

input test
--BOUNDARY
Content-Disposition: form-data; name="openDateTime"

2023-01-01T00:00:00
--BOUNDARY
Content-Disposition: form-data; name="content"

description test
--BOUNDARY
Content-Disposition: form-data; name="files"; filename="uploadSample2.txt"

{ "name": "jane doe" }
--BOUNDARY
Content-Disposition: form-data; name="files"; filename="uploadSample1.txt"

{ "name": "jane doe" }
--BOUNDARY--




 
### 단건 조회
GET {{server}}/noti/detail/10

### 수정
PUT {{server}}/noti/10
Authorization: Bearer {{token}}
Content-Type: multipart/form-data; boundary=BOUNDARY

--BOUNDARY
Content-Disposition: form-data; name="title"

input test updated
--BOUNDARY
Content-Disposition: form-data; name="content"

description test updated
--BOUNDARY
Content-Disposition: form-data; name="openDateTime"

2023-01-01T00:10:00
--BOUNDARY
Content-Disposition: form-data; name="fileIds"

c3182e9a-7315-451c-a064-4046264f6c15
--BOUNDARY
Content-Disposition: form-data; name="fileIds"

33636246-43ec-4491-8332-509f11237d1d
--BOUNDARY
Content-Disposition: form-data; name="files"; filename="uploadSample3.txt"

{ "name": "jane doe" }
--BOUNDARY--


### 삭제
DELETE {{server}}/noti/1
Authorization: Bearer {{token}}