@server=http://localhost:8080

###
GET {{server}}/noti/test

### 목록 조회
GET {{server}}/noti/list
 
### 등록
POST {{server}}/noti/create
Content-Type: application/json

{
  "title": "input test",
  "description": "input test content",
  "openDateTime": "2023-01-01T00:00:00",
  "fileUrlList": ["url1", "url2"]
}
 
### 단건 조회
GET {{server}}/noti/2

### 수정
PUT {{server}}/noti/1
Content-Type: application/json

{
  "title": "input test updated",
  "description": "input test content",
  "openDateTime": "",
  "fileUrlList": ["url1", "url2"]
}

### 삭제
DELETE {{server}}/noti/1