version '3.7'

volumes:
  prometheus_data: {}
  grafana_data: {}

networks:
  front-tier:
  back-tier:
    driver: bridge

services:
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/:/etc/prometheus/
      - ./prometheus_data:/prometheus
    command: 
      - '--config.file=/etc/prometheus/prometheus.yml'